FILEO PRINTO[1] = "{SCENARIO_DIR}\User_Input_Log.PRN"

PRINT CSV=T, LIST= 'Input Files'(50L), PRINTO=1
PRINT CSV=T, LIST= 'Network File'(50L), '{Network}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Toll Link File'(50L), '{Toll Link File}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Toll Link FTYPE Number'(50L), '{Toll Link FTYPE Number}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'HOV Link FTYPE Number'(50L), '{HOV Link FTYPE Number}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Trip Table Type'(50L), '{Trip Table Type}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Trip Table File'(50L), '{Trip Table}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Hourly Distribution File'(50L), '{Hourly Distribution File}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Hourly Parameters'(50L), '{Hourly Parameters}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Zones in Direction 1'(50L), '{Zones in Direction 1}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Number of Zones'(50L), '{Number of Zones}'(90L),PRINTO=1

PRINT CSV=T, LIST= 'Assignment Parameters'(50L), PRINTO=1
PRINT CSV=T, LIST= 'Assignment Method'(50L), '{Assignment Method}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Max Iteration'(50L), '{Max Iteration}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Relative Gap'(50L), '{Relative Gap}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Min Link Congested Speed'(50L), '{Min Link Congested Speed}'(90L),PRINTO=1

PRINT CSV=T, LIST= 'Toll Policy'(50L),PRINTO=1
PRINT CSV=T, LIST= 'Minimum Per Mile Toll'(50L), '{Min Per Mile Toll}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Maximum Per Mile Toll'(50L), '{Max Per Mile Toll}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Minimum Per Segment Toll'(50L), '{Min Per Segment Toll}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Use Minimum Per Segment Toll in Network'(50L), '{Override Minimum Per Segment Toll in Network}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Minimum Per Trip Toll'(50L), '{Min Trip Toll}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'HOV Discount Rate'(50L), '{HOV Discount Rate}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Toll Policy Curve Exponent Coefficient'(50L), '{Toll Exponent}'(90L),PRINTO=1

PRINT CSV=T, LIST= 'Volume Delay Function Parameters'(50L),PRINTO=1
PRINT CSV=T, LIST= 'Volume Delay Function'(50L), '{Volume Delay Function}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Akcelik P'(50L), '{Akcelik P}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Akcelik T'(50L), '{Akcelik T}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Akcelik pb'(50L), '{Akcelik pb}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Akcelik Offset'(50L), '{Akcelik Offset}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'BPR Alpha'(50L), '{BPR Alpha}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'BPR Beta'(50L), '{BPR Beta}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Use BPR Coefficients in Network'(50L), '{Override BPR Coefficients in Network}'(90L),PRINTO=1

PRINT CSV=T, LIST= 'Choice Model Coefficients'(50L),PRINTO=1
PRINT CSV=T, LIST= 'Toll Coefficient (beta)'(50L), '{Toll Coefficient}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Travel Time Coefficient (alpha)'(50L), '{Travel Time Coefficient}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Reliability Coefficient'(50L), '{Reliability Coefficient}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Scale Coefficient (theta)'(50L), '{Scale Coefficient}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Distance Penalty Y'(50L), '{Distance Penalty Y}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Distance Penalty X'(50L), '{Distance Penalty X}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Entropy Scalar'(50L), '{Entropy Scalar}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Entropy Constant'(50L), '{Entropy Constant}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Entropy Beta VC'(50L), '{Entropy Beta VC}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'Time Savings Bias Factor'(50L), '{Time Saving Bias Factor}'(90L),PRINTO=1
PRINT CSV=T, LIST= 'VC Toll Offset'(50L), '{VC Toll Offset}'(90L),PRINTO=1


